### ISSUE TITLE
CFromPtr builtin

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/CompilerDoc#1]
Currently, in hybrid compilation mode, it's trivial to generate a $c0-derived capability from a pointer using a `__capability` cast of that pointer. However, sometimes one wishes to convert a pointer to a capability relative to another capability than $c0 -- for example, $pcc, when deriving executable subcapabilities from the program counter, as might occur during sandbox creation (e.g., in `libcheri`). This arises if neither $c0 nor $pcc is a superset of the other -- e.g., if $c0 is non-executable, and $pcc is non-writable. For function pointers, the compiler is able to figure out that a $pcc-derived capability is required -- but during sandbox construction, we'd rather be explicit (and, in fact, are dealing with sandbox binaries as opaque entities so might prefer not to cast their pointers to function pointers that are statically considered callable) -- and we also will be pushing bounds around, and may need the pointer to be bounds-relative. A new `__builtin_cheri_cap_from_ptr` that accepts a capability argument and a pointer (or perhaps pointer-esque) argument would do the trick nicely, and might see other similar uses in low-level language parts.

**Comment by davidchisnall** [comment]
I don't think that I want to add this, as `CFromPtr` is intended for use by compilers.  Other code should probably do a set-offset with its own error checking.
