### ISSUE TITLE
Document the relationship of intmax_t to intcap_t

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/CompilerDoc#2]
We need to document and our approach to `intmax_t` being `int64_t` not `intcap_t`.  I concur with the reading that we're within the spec in that `intmax_t` can hold the integer range that `intcap_t` can, but there will be bugs if a user assumes they can do `(void *)(intmax_t)(intptr_t)a_pointer`.  On the other side, I'm certain that a fair bit of code assumes that `sizeof(intmax_t)` can be used to compute the range of `intmax_t`

**Comment by brooksdavis** [comment]
If we made `intmax_t` be `intcap_t` then we would need to promote all integer varidac arguments to `intcap_t` since passing `1` and `(intmax_t)1` need to produce the same result if we're going to avoid breaking everything in subtle ways that are impossible to detect at compile time.

**Comment by davidchisnall** [comment]
I think that all sounds sensible (though I'll mark it as 'under investigation' or similar in the doc).  I think FreeBSD (largely due to bde's influence) is the only codebase where I've ever seen intmax_t used, but I might have missed it elsewhere.
