### ISSUE TITLE
New TLS mechanism not documented

### ISSUE THREAD

**Issue by davidchisnall** [CTSRD-CHERI/CompilerDoc#7]
Lots of LLVM commits have landed implementing better TLS support, but there is no associated documentation.

**Comment by jrtc27** [comment]
CHERI-RISC-V's is documented at https://github.com/CTSRD-CHERI/cheri-elf-psabi/blob/master/riscv.md#thread-local-storage (and that whole repo is linked from this one as part of the replacement). CHERI-MIPS is on its way out and not worth documenting.
